### PR TITLE
Feature/convert getPaperInfo to node.js

### PR DESCRIPTION
**Pull request by DarioN555**
Converted the getPaperInfo endpoint to node.js to make it easier for everyone to review and work on if needed.

I'm not too familiar with node.js, so any comments are very welcome.

### CODE REVIEW

**Review by sairaghav — CHANGES_REQUESTED** [review]
Looks good. Just a couple of comments, 
1. When accessing the endpoint from Amplify frontend, the format of input will be slightly different: https://docs.amplify.aws/lib/restapi/fetch/q/platform/js/#accessing-query-parameters--body-in-lambda-proxy-function

2. For storing the key in secret and accessing it with permissions, you need to provide permission to get secret in amplify\backend\function\getPaperInfo\custom-policies.json

**Comment by DarioN555** [comment]
> Looks good. Just a couple of comments,
> 
> 1. When accessing the endpoint from Amplify frontend, the format of input will be slightly different: https://docs.amplify.aws/lib/restapi/fetch/q/platform/js/#accessing-query-parameters--body-in-lambda-proxy-function
> 2. For storing the key in secret and accessing it with permissions, you need to provide permission to get secret in amplify\backend\function\getPaperInfo\custom-policies.json

1. So, I should use `event.body` when accessing the attributes, not just `event`?
Yes, event.body to access the parameters in the request body, as in case of a POST request. Or event.queryStringParameters if you are exposing as a GET request.
2. I thought we were going to set the API key as an environment variable, so I had this approach. Do you think we should use the secret approach?
Yes, I remember we said, we'd implement the env variable first to get used to node and try the secret once we get comfortable with it. I am ok with either, but I thought Ivan wanted to remove it. also, that was just FYI, if you wanted to try it out too.

**Comment by DarioN555** [comment]
@sairaghav 

1. For now, I converted to using `event.body` for now, but I would like to know how this endpoint could be exposed as GET?
2. Okay, we can discuss this on a meeting and decide.

**Comment by DarioN555** [comment]
Some changes added to the PR as a result of doing an amplify pull

**Review by sairaghav — COMMENTED** [review]
Ok. I will try out the endpoints as part of https://smarticle.atlassian.net/browse/SA-106 and will update you in case of more changes. We can have this PR open till then, I guess.

**Review by sairaghav — APPROVED** [review]

**Pull request merged**
