### PR TITLE
Feature/feature tooltip

### PR DESCRIPTION
**Pull request by noemi-i**
# Description

A quick tutorial tooltip will appear at user's first visit to PDF viewer page (through a localStorage item in PdfViewerPage)

## Type of change

- New feature (non-breaking change which adds functionality)

## Screenshots

Screenshot 2022-12-28 alle 15 13 49
Screenshot 2022-12-28 alle 15 14 03
Screenshot 2022-12-28 alle 15 14 11
Screenshot 2022-12-28 alle 15 14 17
Screenshot 2022-12-28 alle 15 14 24

# Reference JIRA tickets : 

- SA-#146

# Checklist:

Put an "x" in the brackets to check the checkbox.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in particularly hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding changes to JIRA tickets
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have merged develop into my branch and resolved possible conflicts

### CODE REVIEW

**Review by sairaghav — CHANGES_REQUESTED** [review]
I don't know if it is for everyone, but after the tour gets over, the icons in the toolbar don't seem to work. 
icons

Also, maybe for the last modal, we can have "Thanks" or something other than "END" as the title?

**Comment by noemi-i** [comment]
> I don't know if it is for everyone, but after the tour gets over, the icons in the toolbar don't seem to work. icons [ icons ](https://user-images.githubusercontent.com/4383992/210247082-0512fd3d-d830-45ab-8186-4a2c68975149.gif) [ ](https://user-images.githubusercontent.com/4383992/210247082-0512fd3d-d830-45ab-8186-4a2c68975149.gif)
> 
> Also, maybe for the last modal, we can have "Thanks" or something other than "END" as the title?

Thank you for the review, you're right, maybe "Thanks/Thank You" is better than simple "End"!

About the Sidebar, I'm not sure why those icons doesn't work, I've tried both on Chrome and Safari and they works normally:
Registrazione schermo 2023-01-02 alle 15 53 35

**Review by vlahovivan — COMMENTED** [review]
For me everything works well, I'm not sure how that error could have happened (tried multiple times both on Brave/Chromium and Firefox)
Also, I think we should put something like "Start reading" or "Tour finished" instead of "END"

**Comment by sanjayssj5** [comment]
Works good for me as well! Tried in Chrome and Mozilla

**Comment by noemi-i** [comment]
> For me everything works well, I'm not sure how that error could have happened (tried multiple times both on Brave/Chromium and Firefox)
> Also, I think we should put something like "Start reading" or "Tour finished" instead of "END"

Thank you for the comment, I just modified the last tooltip with "Tour Finished" as title and "Start Reading" as close button

**Review by vlahovivan — APPROVED** [review]

**Review by sairaghav — APPROVED** [review]
I think it is not related to this specific feature. But sometimes, both on Edge and Firefox, I get the following error: and sidebar does not work
```
Uncaught TypeError: Cannot read properties of null (reading 'files')
    at registerCustomToolbarButtonHandlers (customToolbar.js:6:28)
    at editToolBar (customToolbar.js:93:3)
```

**Comment by vlahovivan** [comment]
@sairaghav thanks, I've found the error, it's not related to this PR, I'll fix it now on another PR, so I think we can merge this now if everyone agrees

**Pull request merged**
